# Generated by Django 2.1.2 on 2018-11-30 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BillboardData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('artist', models.CharField(max_length=100)),
                ('isNew', models.BooleanField()),
                ('lastPos', models.IntegerField()),
                ('peakPos', models.IntegerField()),
                ('rank', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('weeks', models.IntegerField()),
            ],
        ),
    ]
